### ISSUE TITLE
Opt4J Homepage

### ISSUE THREAD

**Issue by michaelhglass** [SDARG/opt4j#33]
Using the Ohloh plugin on http://opt4j.org as an example, I think we should discuss which information we want to gather on the homepage vs. just having them here in GitHub. Is the homepage still our preferred way to access Opt4J, then we should discuss which information to keep and how to keep it updated (Contributors, Screenshots, Versions, Tutorial etc.). If we want to redirect more people to the GitHub page (which contains almost everything as well), then we should reshape the homepage to redirect people to the GitHub page and maybe move tutorial etc. to the Wiki.
What's your opinion?

**Comment by felixreimann** [comment]
Does it make sense to seperate between users and developers? Then, we could add all information for users to the website and all information for developers to github readme and wiki.
Accordingly, examples for website content could be
* tutorial
* documentation
* list of publications
while examples for Github wiki could be
* release notes
* gradle task descriptions

However, as you are required to interact with opt4j with its Java API, this separation might not be too sharp.

**Comment by FedorSmirnov89** [comment]
As discussed today, it is probably preferable to have only one source of information about Opt4J. I would prefer to keep everything in the GitHub Wiki and just add a link on the website pointing here.

**Comment by michaelhglass** [comment]
It's seems about time to readdress this issue. I think we have quite an established tutorial and some people might prefer to check for the JavaDoc etc. on the website vs. on the central Javadoc.io. My suggestion would be that I clean the website from all unnecessary stuff and try to redirect the interested developers to Github. If you have ideas, please check for the respective branch.

**Comment by michaelhglass** [comment]
Reworked the website, let's postpone the topic of content of the website to individual aspects such as the tutorial etc.
