### ISSUE TITLE
Code is breaking in newer versions of JDK 

### ISSUE THREAD

**Issue by rgudwin** [SDARG/opt4j#86]
Hi, I am using this library in my project, but it is breaking in newer versions of JDK (17 up to 21). Is there a chance a newer version, compatible with the newer restrictions imposed in Java 17 be released ? 
Apparently, what is breaking is an older version of Guice, which is not running in JDK 17 and beyond:

Nov 07, 2023 11:48:29 AM com.google.inject.internal.MessageProcessor visit
    INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2df9b86
    java.lang.IllegalStateException: Unable to load cache item

**Comment by FedorSmirnov89** [comment]
@rgudwin : Thank you for creating the issue :) . Haven't run Opt for a while myself. I have now set up Java 19 + Gradle 8+ on my machine and bumped all dependencies until the `gradle build` worked and the tests passed. It would be a great help if you could check out the version on the [branch](https://github.com/SDARG/opt4j/tree/version_bump_gradle_java) and see whether everything works on your setup. Thank you.

**Comment by rgudwin** [comment]
Dear Fedor,
I tried here with Java 17. Two side-effects.
If I use, as a dependency (in gradle), just:

api 'com.github.sdarg:opt4j:4780f4e'

it does not compile at all ... !!!
If I do:

api 'com.google.inject:guice:7.0.0'
api 'com.github.sdarg:opt4j:4780f4e'

Then it compiles and runs without exceptions. But I suspect that declaring
guice should not be made by me. I should not have to guess that opt4j
depends on guice ... it should be declared by opt4j and I should declare
dependency only on opt4j, not in guice.

Another side effect: I was not able to compile it with JDK 8 anymore. Just
with JDK 11 and beyond.
Ricardo

**Comment by michaelhglass** [comment]
We will address this issue and bump to Java 21 LTS. See issue #88.
